import type { GoalId, LevelId } from './options.js';

export type CatalogResource = {
  id: string;
  title: string;
  url: string;
  kind: 'docs' | 'course' | 'practice';
  tracks: readonly GoalId[];
  level: LevelId;
};

const py: GoalId[] = ['aiml', 'be', 'fs', 'ds'];

export const localRoadmapResources: CatalogResource[] = [
  {
    id: 'py',
    title: 'Python Tutorial',
    url: 'https://docs.python.org/3/tutorial/',
    kind: 'docs',
    tracks: py,
    level: 'beg',
  },
  {
    id: 'git',
    title: 'Git Handbook',
    url: 'https://docs.github.com/en/get-started/git-basics/set-up-git',
    kind: 'docs',
    tracks: ['aiml', 'be', 'fs', 'ds', 'ops'],
    level: 'beg',
  },
  {
    id: 'sql',
    title: 'PostgreSQL Tutorial',
    url: 'https://www.postgresql.org/docs/current/tutorial.html',
    kind: 'docs',
    tracks: ['be', 'fs', 'ds', 'ops'],
    level: 'beg',
  },
  {
    id: 'mdn',
    title: 'MDN Learn Web',
    url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development',
    kind: 'docs',
    tracks: ['fs', 'be'],
    level: 'beg',
  },
  {
    id: 'http',
    title: 'MDN HTTP',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
    kind: 'docs',
    tracks: ['be', 'fs', 'ops'],
    level: 'some',
  },
  {
    id: 'np',
    title: 'NumPy Beginner',
    url: 'https://numpy.org/doc/stable/user/absolute_beginners.html',
    kind: 'docs',
    tracks: ['aiml', 'ds'],
    level: 'beg',
  },
  {
    id: 'pd',
    title: 'Pandas Getting Started',
    url: 'https://pandas.pydata.org/docs/getting_started/index.html',
    kind: 'docs',
    tracks: ['aiml', 'ds'],
    level: 'beg',
  },
  {
    id: 'sk',
    title: 'scikit-learn User Guide',
    url: 'https://scikit-learn.org/stable/user_guide.html',
    kind: 'docs',
    tracks: ['aiml', 'ds'],
    level: 'some',
  },
  {
    id: 'kpy',
    title: 'Kaggle Learn Python',
    url: 'https://www.kaggle.com/learn/python',
    kind: 'course',
    tracks: ['aiml', 'ds'],
    level: 'beg',
  },
  {
    id: 'kml',
    title: 'Kaggle Intro to ML',
    url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
    kind: 'course',
    tracks: ['aiml', 'ds'],
    level: 'some',
  },
  {
    id: 'csai',
    title: 'CS50 AI',
    url: 'https://cs50.harvard.edu/ai/',
    kind: 'course',
    tracks: ['aiml'],
    level: 'int',
  },
  {
    id: 'pt',
    title: 'PyTorch Tutorials',
    url: 'https://pytorch.org/tutorials/',
    kind: 'docs',
    tracks: ['aiml'],
    level: 'int',
  },
  {
    id: 'fa',
    title: 'fast.ai Course',
    url: 'https://course.fast.ai/',
    kind: 'course',
    tracks: ['aiml'],
    level: 'int',
  },
  {
    id: 'kj',
    title: 'Kaggle Learn SQL',
    url: 'https://www.kaggle.com/learn/intro-to-sql',
    kind: 'course',
    tracks: ['ds', 'be'],
    level: 'beg',
  },
  {
    id: 'kpd',
    title: 'Kaggle Pandas',
    url: 'https://www.kaggle.com/learn/pandas',
    kind: 'course',
    tracks: ['ds'],
    level: 'beg',
  },
  {
    id: 'kdv',
    title: 'Kaggle Data Viz',
    url: 'https://www.kaggle.com/learn/data-visualization',
    kind: 'course',
    tracks: ['ds'],
    level: 'some',
  },
  {
    id: 'kfe',
    title: 'Kaggle Feature Engineering',
    url: 'https://www.kaggle.com/learn/feature-engineering',
    kind: 'course',
    tracks: ['ds', 'aiml'],
    level: 'int',
  },
  {
    id: 'fx',
    title: 'FastAPI Tutorial',
    url: 'https://fastapi.tiangolo.com/tutorial/',
    kind: 'docs',
    tracks: ['be', 'aiml', 'ds'],
    level: 'some',
  },
  {
    id: 'node',
    title: 'Node.js Guides',
    url: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs',
    kind: 'docs',
    tracks: ['be', 'fs'],
    level: 'beg',
  },
  {
    id: 'ex',
    title: 'Express Guide',
    url: 'https://expressjs.com/en/starter/installing.html',
    kind: 'docs',
    tracks: ['be', 'fs'],
    level: 'some',
  },
  {
    id: 'react',
    title: 'React Learn',
    url: 'https://react.dev/learn',
    kind: 'docs',
    tracks: ['fs'],
    level: 'some',
  },
  {
    id: 'fcc',
    title: 'freeCodeCamp JS',
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    kind: 'course',
    tracks: ['fs', 'be'],
    level: 'beg',
  },
  {
    id: 'dock',
    title: 'Docker Get Started',
    url: 'https://docs.docker.com/get-started/',
    kind: 'docs',
    tracks: ['ops', 'be', 'fs'],
    level: 'beg',
  },
  {
    id: 'lin',
    title: 'Linux Journey',
    url: 'https://linuxjourney.com/',
    kind: 'course',
    tracks: ['ops'],
    level: 'beg',
  },
  {
    id: 'k8s',
    title: 'Kubernetes Basics',
    url: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
    kind: 'docs',
    tracks: ['ops'],
    level: 'int',
  },
  {
    id: 'ghact',
    title: 'GitHub Actions',
    url: 'https://docs.github.com/en/actions/get-started/quickstart',
    kind: 'docs',
    tracks: ['ops', 'fs', 'be'],
    level: 'some',
  },
  {
    id: 'tf',
    title: 'Terraform Tutorials',
    url: 'https://developer.hashicorp.com/terraform/tutorials',
    kind: 'docs',
    tracks: ['ops'],
    level: 'int',
  },
  {
    id: 'prom',
    title: 'Prometheus First Steps',
    url: 'https://prometheus.io/docs/prometheus/latest/getting_started/',
    kind: 'docs',
    tracks: ['ops'],
    level: 'int',
  },
  {
    id: 'leet',
    title: 'NeetCode Roadmap',
    url: 'https://neetcode.io/roadmap',
    kind: 'practice',
    tracks: ['be', 'fs', 'aiml', 'ds'],
    level: 'int',
  },
];

export function resourceById(id: string): CatalogResource | undefined {
  return localRoadmapResources.find((item) => item.id === id);
}
