export const yearRoadmaps: Record<string, string> = {
  '1': [
    '## First Year Roadmap',
    '**Goal:** Build a programming habit, understand how computers work, and finish Year 1 subjects without cramming.',
    '',
    '### What Year 1 is for',
    'This year is foundations. Grades matter, but **daily coding** matters more. If you can write small programs, use Git, and explain loops, arrays, and functions, you are on track.',
    '',
    '### Subjects to take seriously',
    '- Programming (C / C++ / Python / Java — follow your college syllabus)',
    '- Computer fundamentals & digital logic',
    '- Discrete mathematics',
    '- Mathematics (especially sets, logic, matrices)',
    '- Communication / English for reports and viva',
    '- Any intro IT / office / web paper',
    '',
    '### Skills to finish this year',
    '1. One language fluently enough to solve basic problems without copying',
    '2. Git + GitHub (init, commit, push, README)',
    '3. HTML + CSS for a simple personal page',
    '4. Typing, folders, terminal basics',
    '5. How to read an error message and debug it',
    '',
    '### Semester plan',
    '**Sem 1**',
    '- Code 45–60 minutes every day, even if the assignment is tiny',
    '- Finish one beginner course in your syllabus language (not five courses)',
    '- Make 8–10 small programs: calculator, number guessing, student marks, pattern printing',
    '- Learn Git in week 3–4 and put those programs on GitHub',
    '',
    '**Sem 2**',
    '- Functions, arrays, strings, file handling, simple structs / classes if taught',
    '- Discrete math: sets, relations, graphs at a basic level — this pays off in DSA later',
    '- Build one mini project: library list, quiz app, or expense tracker (console is fine)',
    '- Start LeetCode / HackerRank **easy** — 2 problems a week, not a grind yet',
    '',
    '### Weekly habit (keep this all 3 years)',
    '- 5 days code, 1 day notes / revision, 1 day off',
    '- After every lab: rewrite the program from memory the same night',
    '- One GitHub commit per week minimum',
    '',
    '### Free starting points',
    '- [freeCodeCamp](https://www.freecodecamp.org/) — programming + web',
    '- [CS50x](https://cs50.harvard.edu/x/) — how computers and C actually work',
    '- [Python.org tutorial](https://docs.python.org/3/tutorial/) if your lab uses Python',
    '- [The Odin Project Foundations](https://www.theodinproject.com/paths/foundations) — HTML/CSS/Git',
    '- [GitHub Skills](https://skills.github.com/) — Git without panic',
    '',
    '### Tips',
    '- College PDFs are enough for theory exams. YouTube is for *doing*.',
    '- Do not hop languages. Master the one your college uses first.',
    '- If you are stuck 30 minutes, write what you tried, then ask — that is how you learn.',
    '- First-year project does not need React. Working code + a README beats a fancy UI you cannot explain.',
  ].join('\n'),

  '2': [
    '## Second Year Roadmap',
    '**Goal:** Become a real CS student — DSA, databases, OS, OOP, and a web project you can demo.',
    '',
    '### What Year 2 is for',
    'This is the year internships start noticing you. Internships want: one language, basic DSA, SQL, and a project with a README. Theory papers (OS, DBMS, SE) are also the ones companies probe in interviews.',
    '',
    '### Subjects to take seriously',
    '- Data structures & algorithms',
    '- OOP',
    '- DBMS + SQL',
    '- Operating systems',
    '- Computer networks (intro)',
    '- Software engineering',
    '- Web / Java / Python papers your college runs',
    '',
    '### Skills to finish this year',
    '1. Arrays, strings, hashing, stacks, queues, linked lists, trees — with Big-O intuition',
    '2. SQL: SELECT, JOIN, GROUP BY, indexes at a basic level',
    '3. OOP: classes, inheritance, when *not* to inherit',
    '4. A full-stack or backend mini app (auth + CRUD is enough)',
    '5. Linux basics and how a process / thread / HTTP request works in plain English',
    '',
    '### Semester plan',
    '**Sem 3**',
    '- Pick a DSA sheet and stay on it (Striver / NeetCode 150 — easy then medium)',
    '- Target ~100 easy/medium problems by end of year, not 500 rushed ones',
    '- DBMS: draw ER diagrams for 2 real systems (library, hostel, store)',
    '- Start a web project: notes app, issue tracker, or campus event site',
    '',
    '**Sem 4**',
    '- Finish the project: login, database, deploy (Render / Railway / Vercel / any free host)',
    '- OS: process vs thread, deadlock, scheduling — interview favorites',
    '- Networks: OSI vs TCP/IP, HTTP, DNS, what a port is',
    '- Apply to internships even if you feel underqualified. Resume + GitHub + 1 project.',
    '',
    '### Project bar (this year)',
    'Not a to-do clone with no backend. Aim for:',
    '- Real users (even 5 classmates)',
    '- A database',
    '- Error handling',
    '- README with screenshots and how to run it',
    '',
    '### Free starting points',
    '- [NeetCode Roadmap](https://neetcode.io/roadmap)',
    '- [VisuAlgo](https://visualgo.net/) — see structures move',
    '- [SQLBolt](https://sqlbolt.com/) + [Mode SQL tutorial](https://mode.com/sql-tutorial/)',
    '- [MDN Web Docs](https://developer.mozilla.org/) — HTML/CSS/JS reference',
    '- [The Odin Project](https://www.theodinproject.com/) or [full-stack-open](https://fullstackopen.com/en/)',
    '- [Operating Systems: Three Easy Pieces](https://pages.cs.wisc.edu/~remzi/OSTEP/) — readable OS book',
    '- [Missing Semester](https://missing.csail.mit.edu/) — shell, Git, debugging',
    '',
    '### Tips',
    '- DSA without a notebook is wasted. Write the pattern (two pointers, sliding window) in 5 lines after each topic.',
    '- SQL is the fastest internship skill per hour spent. Practice on your own sample data.',
    '- Group projects: own one module completely so you can talk about it in interviews.',
    '- Start a simple resume now. Update it every time you finish a project or lab worth showing.',
  ].join('\n'),

  '3': [
    '## Third Year Roadmap',
    '**Goal:** Graduate with internships, a strong project, interview readiness, and a direction (job, MCA, or both).',
    '',
    '### What Year 3 is for',
    'Placements and internships. You do not need every new framework. You need **depth in one stack**, **DSA you can perform under pressure**, and **stories** about projects you actually built.',
    '',
    '### Subjects to take seriously',
    '- Remaining core: networks, compiler / TOC if in syllabus, electives',
    '- Project / internship / seminar papers — treat these as portfolio, not filler',
    '- Electives: pick AI/ML, cloud, security, or mobile based on the job you want',
    '',
    '### Pick a lane (do not pick four)',
    '- **Software job:** DSA + one backend or full-stack + system-design basics + 2 projects',
    '- **Data / ML:** Python, SQL, pandas, one ML project with a real dataset, math revision',
    '- **MCA / further study:** keep CGPA healthy, revise discrete math + OS + DBMS + TOC',
    '',
    '### Skills to finish this year',
    '1. Interview DSA: arrays, hashing, trees, graphs, DP at a basic–medium level',
    '2. Explain your project: problem, architecture, hardest bug, what you would redo',
    '3. GitHub that looks like a person who ships (pinned repos, clear READMEs)',
    '4. Resume one page, numbers where possible (users, load time, test coverage)',
    '5. Aptitude + core CS MCQs your campus drives use',
    '',
    '### Semester plan',
    '**Sem 5**',
    '- Capstone: start early. Weekly demos to yourself. Frozen feature list.',
    '- 4–5 DSA days a week if you want product / service companies',
    '- Apply on internshala, LinkedIn, company careers, referrals — volume matters',
    '- Mock interviews with a friend: 45 min DSA + 15 min project',
    '',
    '**Sem 6**',
    '- Polish capstone, write a short case-study in the README',
    '- Core revision sheet: OS, DBMS, CN, OOP — 2 pages each',
    '- If job hunt: 2 applications a day until you have interviews',
    '- If MCA: previous-year papers + quantitative + reasoning on a calendar',
    '',
    '### Final-year project bar',
    '- A problem someone besides you cares about',
    '- Auth, data model, and one non-trivial feature (search, reports, realtime, ML inference, payments sandbox, etc.)',
    '- Deployed or a recorded demo',
    '- Honest limitations section',
    '',
    '### Free starting points',
    '- [NeetCode](https://neetcode.io/) / [LeetCode Patterns](https://seanprashad.com/leetcode-patterns/)',
    '- [System Design Primer](https://github.com/donnemartin/system-design-primer) — light pass only',
    '- [CS50 AI](https://cs50.harvard.edu/ai/) if you chose the ML lane',
    '- [Kaggle Learn](https://www.kaggle.com/learn) — short practical ML/data',
    '- [Cloud skills boost / AWS free tier labs](https://www.aws.training/) if you chose DevOps/cloud',
    '- [Tech Interview Handbook](https://www.techinterviewhandbook.org/)',
    '',
    '### Tips',
    '- Companies hire proof, not potential. Ship, then talk.',
    '- One excellent project beats four unfinished clones.',
    '- Learn enough system design to draw your own app: clients, server, DB, cache.',
    '- Sleep and consistency beat 14-hour panic weeks before drives.',
    '- Keep notes of every interview question you miss. That list is your last-month syllabus.',
  ].join('\n'),
};

export function getYearRoadmap(yearId: string): string | undefined {
  return yearRoadmaps[yearId];
}
